apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: requeststates.com.redhat.ecosystem.sample
spec:
  group: com.redhat.ecosystem.sample
  scope: Namespaced
  names:
    kind: RequestState
    listKind: RequestStateList
    plural: requeststates
    singular: requeststate
  subresources:
    status: {}
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        # openAPIV3Schema is the schema for validating custom objects.
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["request-uid","job","state"]
              properties:
                request-uid:
                  type: "string"
                  minimum: 1
                job:
                  type: "string"
                  minimum: 1
                state:
                  type: "string"
                  minimum: 1
            status:
              type: object
              properties:
                history:
                  type: "array"
                  items:
                    type: object
                    required: ["job","state","timestamp"]
                    properties:
                      job:
                        type: "string"
                        minimum: 1
                      state:
                        type: "string"
                        minimum: 1
                      timestamp:
                        type: "string"
                        minimum: 1            